2021/05/20 13:14:58 INFO  [main] - Starting Application using Java 11.0.10 on FNDM35.local with PID 64430 (/Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1/build/classes/java/main started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 13:14:58 INFO  [main] - No active profile set, falling back to default profiles: default
2021/05/20 13:14:58 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 13:15:01 INFO  [main] - Tomcat initialized with port(s): 8080 (http)
2021/05/20 13:15:01 INFO  [main] - Initializing ProtocolHandler ["http-nio-8080"]
2021/05/20 13:15:01 INFO  [main] - Starting service [Tomcat]
2021/05/20 13:15:01 INFO  [main] - Starting Servlet engine: [Apache Tomcat/9.0.44]
2021/05/20 13:15:02 INFO  [main] - Initializing Spring embedded WebApplicationContext
2021/05/20 13:15:02 INFO  [main] - Root WebApplicationContext: initialization completed in 3237 ms
2021/05/20 13:15:02 INFO  [main] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 13:15:03 INFO  [main] - HikariPool-1 - Starting...
2021/05/20 13:15:04 ERROR [main] - HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:223)
	at com.sun.proxy.$Proxy80.getMetaData(Unknown Source)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:340)
	at org.springframework.jdbc.support.SQLErrorCodesFactory.resolveErrorCodes(SQLErrorCodesFactory.java:235)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.lambda$setDataSource$0(SQLErrorCodeSQLExceptionTranslator.java:140)
	at org.springframework.util.function.SingletonSupplier.get(SingletonSupplier.java:97)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:141)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:102)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration.exceptionTranslator(DomaAutoConfiguration.java:119)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c.CGLIB$exceptionTranslator$7(<generated>)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c$$FastClassBySpringCGLIB$$fbc3775.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c.exceptionTranslator(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at jp.co.froide.javaframework.Application.main(Application.java:10)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	... 52 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 55 common frames omitted
2021/05/20 13:15:04 WARN  [main] - Error while extracting database name
org.springframework.jdbc.support.MetaDataAccessException: Error while extracting DatabaseMetaData; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:366)
	at org.springframework.jdbc.support.SQLErrorCodesFactory.resolveErrorCodes(SQLErrorCodesFactory.java:235)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.lambda$setDataSource$0(SQLErrorCodeSQLExceptionTranslator.java:140)
	at org.springframework.util.function.SingletonSupplier.get(SingletonSupplier.java:97)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.setDataSource(SQLErrorCodeSQLExceptionTranslator.java:141)
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.<init>(SQLErrorCodeSQLExceptionTranslator.java:102)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration.exceptionTranslator(DomaAutoConfiguration.java:119)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c.CGLIB$exceptionTranslator$7(<generated>)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c$$FastClassBySpringCGLIB$$fbc3775.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.seasar.doma.boot.autoconfigure.DomaAutoConfiguration$$EnhancerBySpringCGLIB$$caf7919c.exceptionTranslator(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:769)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302)
	at jp.co.froide.javaframework.Application.main(Application.java:10)
Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:223)
	at com.sun.proxy.$Proxy80.getMetaData(Unknown Source)
	at org.springframework.jdbc.support.JdbcUtils.extractDatabaseMetaData(JdbcUtils.java:340)
	... 37 common frames omitted
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:144)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:953)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:823)
	... 52 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:155)
	at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63)
	... 55 common frames omitted
2021/05/20 13:15:05 INFO  [main] - Starting ProtocolHandler ["http-nio-8080"]
2021/05/20 13:15:05 INFO  [main] - Tomcat started on port(s): 8080 (http) with context path ''
2021/05/20 13:15:05 INFO  [main] - Started Application in 8.496 seconds (JVM running for 9.923)
2021/05/20 13:15:28 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 13:20:02 INFO  [main] - Starting Application using Java 11.0.10 on FNDM35.local with PID 64506 (/Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1/build/classes/java/main started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 13:20:02 INFO  [main] - No active profile set, falling back to default profiles: default
2021/05/20 13:20:02 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 13:20:05 INFO  [main] - Tomcat initialized with port(s): 8080 (http)
2021/05/20 13:20:05 INFO  [main] - Initializing ProtocolHandler ["http-nio-8080"]
2021/05/20 13:20:05 INFO  [main] - Starting service [Tomcat]
2021/05/20 13:20:05 INFO  [main] - Starting Servlet engine: [Apache Tomcat/9.0.44]
2021/05/20 13:20:05 INFO  [main] - Initializing Spring embedded WebApplicationContext
2021/05/20 13:20:05 INFO  [main] - Root WebApplicationContext: initialization completed in 3122 ms
2021/05/20 13:20:06 INFO  [main] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 13:20:07 INFO  [main] - HikariPool-1 - Starting...
2021/05/20 13:20:08 INFO  [main] - HikariPool-1 - Start completed.
2021/05/20 13:20:09 INFO  [main] - Starting ProtocolHandler ["http-nio-8080"]
2021/05/20 13:20:09 INFO  [main] - Tomcat started on port(s): 8080 (http) with context path ''
2021/05/20 13:20:09 INFO  [main] - Started Application in 9.098 seconds (JVM running for 10.271)
2021/05/20 13:20:46 INFO  [http-nio-8080-exec-1] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2021/05/20 13:20:46 INFO  [http-nio-8080-exec-1] - Initializing Servlet 'dispatcherServlet'
2021/05/20 13:20:47 INFO  [http-nio-8080-exec-1] - Completed initialization in 4 ms
2021/05/20 13:44:53 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 13:44:53 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 13:44:53 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
2021/05/20 14:18:10 INFO  [main] - Starting Application using Java 11.0.10 on FNDM35.local with PID 64913 (/Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1/build/classes/java/main started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 14:18:10 INFO  [main] - No active profile set, falling back to default profiles: default
2021/05/20 14:18:10 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 14:18:13 INFO  [main] - Tomcat initialized with port(s): 8080 (http)
2021/05/20 14:18:13 INFO  [main] - Initializing ProtocolHandler ["http-nio-8080"]
2021/05/20 14:18:13 INFO  [main] - Starting service [Tomcat]
2021/05/20 14:18:13 INFO  [main] - Starting Servlet engine: [Apache Tomcat/9.0.44]
2021/05/20 14:18:13 INFO  [main] - Initializing Spring embedded WebApplicationContext
2021/05/20 14:18:13 INFO  [main] - Root WebApplicationContext: initialization completed in 2989 ms
2021/05/20 14:18:13 INFO  [main] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 14:18:14 INFO  [main] - HikariPool-1 - Starting...
2021/05/20 14:18:15 INFO  [main] - HikariPool-1 - Start completed.
2021/05/20 14:18:15 INFO  [main] - Starting ProtocolHandler ["http-nio-8080"]
2021/05/20 14:18:15 INFO  [main] - Tomcat started on port(s): 8080 (http) with context path ''
2021/05/20 14:18:15 INFO  [main] - Started Application in 7.384 seconds (JVM running for 8.506)
2021/05/20 14:18:21 INFO  [http-nio-8080-exec-1] - Initializing Spring DispatcherServlet 'dispatcherServlet'
2021/05/20 14:18:21 INFO  [http-nio-8080-exec-1] - Initializing Servlet 'dispatcherServlet'
2021/05/20 14:18:21 INFO  [http-nio-8080-exec-1] - Completed initialization in 2 ms
2021/05/20 14:24:58 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 14:24:58 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 14:24:58 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
2021/05/20 16:49:49 INFO  [Test worker] - Starting UserControllerTest using Java 11.0.10 on FNDM35.local with PID 65755 (started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 16:49:49 INFO  [Test worker] - No active profile set, falling back to default profiles: default
2021/05/20 16:49:49 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 16:49:55 INFO  [Test worker] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 16:49:57 INFO  [Test worker] - HikariPool-1 - Starting...
2021/05/20 16:49:58 INFO  [Test worker] - HikariPool-1 - Start completed.
2021/05/20 16:49:58 INFO  [Test worker] - Started UserControllerTest in 10.852 seconds (JVM running for 14.105)
2021/05/20 16:50:00 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 16:50:00 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 16:50:00 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
2021/05/20 16:54:35 INFO  [Test worker] - Starting UserControllerTest using Java 11.0.10 on FNDM35.local with PID 65795 (started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 16:54:35 INFO  [Test worker] - No active profile set, falling back to default profiles: default
2021/05/20 16:54:36 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 16:54:42 INFO  [Test worker] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 16:54:43 INFO  [Test worker] - HikariPool-1 - Starting...
2021/05/20 16:54:44 INFO  [Test worker] - HikariPool-1 - Start completed.
2021/05/20 16:54:45 INFO  [Test worker] - Started UserControllerTest in 10.495 seconds (JVM running for 14.779)
2021/05/20 16:54:47 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 16:54:47 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 16:54:47 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
2021/05/20 16:59:57 INFO  [Test worker] - Starting UserControllerTest using Java 11.0.10 on FNDM35.local with PID 65820 (started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 16:59:57 INFO  [Test worker] - No active profile set, falling back to default profiles: default
2021/05/20 16:59:57 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 17:00:02 INFO  [Test worker] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 17:00:03 INFO  [Test worker] - HikariPool-1 - Starting...
2021/05/20 17:00:04 INFO  [Test worker] - HikariPool-1 - Start completed.
2021/05/20 17:00:04 INFO  [Test worker] - Started UserControllerTest in 8.662 seconds (JVM running for 12.087)
2021/05/20 17:00:07 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 17:00:07 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 17:00:07 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
2021/05/20 17:05:41 INFO  [Test worker] - Starting UserControllerTest using Java 11.0.10 on FNDM35.local with PID 65921 (started by kazutoshi-asao in /Users/kazutoshi-asao/Documents/springBoot/java-framework/src/examples/ch3_1)
2021/05/20 17:05:41 INFO  [Test worker] - No active profile set, falling back to default profiles: default
2021/05/20 17:05:41 INFO  [background-preinit] - HV000001: Hibernate Validator 6.1.7.Final
2021/05/20 17:05:45 INFO  [Test worker] - Initializing ExecutorService 'applicationTaskExecutor'
2021/05/20 17:05:46 INFO  [Test worker] - HikariPool-1 - Starting...
2021/05/20 17:05:47 INFO  [Test worker] - HikariPool-1 - Start completed.
2021/05/20 17:05:48 INFO  [Test worker] - Started UserControllerTest in 8.082 seconds (JVM running for 10.984)
2021/05/20 17:05:50 INFO  [SpringContextShutdownHook] - Shutting down ExecutorService 'applicationTaskExecutor'
2021/05/20 17:05:50 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown initiated...
2021/05/20 17:05:50 INFO  [SpringContextShutdownHook] - HikariPool-1 - Shutdown completed.
